import { Recipe } from "./types";

export const sampleRecipes: Recipe[] = [
  {
    id: "1",
    slug: "classic-margherita-pizza",
    title: "Classic Margherita Pizza",
    description:
      "A simple, authentic Italian pizza with fresh mozzarella, San Marzano tomatoes, and basil on a crispy thin crust.",
    ingredients: [
      "2 1/4 tsp active dry yeast",
      "1 cup warm water",
      "3 cups all-purpose flour",
      "1 tsp salt",
      "1 tbsp olive oil",
      "1 can (14 oz) San Marzano tomatoes",
      "8 oz fresh mozzarella",
      "Fresh basil leaves",
      "Extra virgin olive oil for drizzling",
    ],
    steps: [
      "Dissolve yeast in warm water and let sit for 5 minutes until foamy.",
      "Mix flour and salt, add yeast mixture and olive oil. Knead for 8 minutes until smooth.",
      "Let dough rise in a covered bowl for 1 hour until doubled.",
      "Preheat oven to 500°F with a pizza stone if available.",
      "Crush San Marzano tomatoes by hand for the sauce.",
      "Stretch dough into a 12-inch round on a floured surface.",
      "Spread crushed tomatoes, tear mozzarella over the top.",
      "Bake for 8-10 minutes until crust is golden and cheese is bubbly.",
      "Top with fresh basil and a drizzle of olive oil before serving.",
    ],
    tags: ["Italian", "Pizza", "Vegetarian"],
    prepTime: 20,
    cookTime: 10,
    servings: 4,
    isFavorite: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "2",
    slug: "thai-green-curry",
    title: "Thai Green Curry",
    description:
      "A fragrant and creamy coconut curry loaded with vegetables and aromatic Thai green curry paste.",
    ingredients: [
      "2 tbsp green curry paste",
      "1 can (14 oz) coconut milk",
      "1 lb chicken thighs, sliced",
      "1 cup bamboo shoots",
      "1 red bell pepper, sliced",
      "1 cup Thai basil leaves",
      "2 tbsp fish sauce",
      "1 tbsp palm sugar",
      "4 kaffir lime leaves",
      "Jasmine rice for serving",
    ],
    steps: [
      "Heat a splash of coconut cream in a wok over high heat.",
      "Add green curry paste and fry for 1 minute until fragrant.",
      "Add chicken and stir-fry until no longer pink on the outside.",
      "Pour in coconut milk and bring to a gentle simmer.",
      "Add bamboo shoots, bell pepper, and kaffir lime leaves.",
      "Season with fish sauce and palm sugar. Simmer for 15 minutes.",
      "Stir in Thai basil just before serving.",
      "Serve over steamed jasmine rice.",
    ],
    tags: ["Thai", "Curry", "Spicy"],
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    isFavorite: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "3",
    slug: "lemon-herb-roasted-chicken",
    title: "Lemon Herb Roasted Chicken",
    description:
      "A beautifully golden whole roasted chicken with lemon, garlic, and fresh herbs. Perfect Sunday dinner.",
    ingredients: [
      "1 whole chicken (4-5 lbs)",
      "2 lemons",
      "1 head of garlic",
      "4 sprigs fresh rosemary",
      "6 sprigs fresh thyme",
      "3 tbsp butter, softened",
      "Salt and pepper",
      "1 lb baby potatoes",
      "2 carrots, chopped",
    ],
    steps: [
      "Preheat oven to 425°F. Pat chicken dry with paper towels.",
      "Mix softened butter with chopped rosemary, thyme, lemon zest, salt, and pepper.",
      "Rub herb butter all over the chicken and under the skin.",
      "Stuff cavity with halved lemons and garlic head.",
      "Arrange potatoes and carrots around the chicken in a roasting pan.",
      "Roast for 1 hour 15 minutes until internal temp reaches 165°F.",
      "Let rest for 15 minutes before carving.",
      "Serve with pan vegetables and drippings.",
    ],
    tags: ["Dinner", "Roast", "Classic"],
    prepTime: 20,
    cookTime: 75,
    servings: 6,
    isFavorite: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "4",
    slug: "chocolate-lava-cake",
    title: "Chocolate Lava Cake",
    description:
      "Rich, decadent individual chocolate cakes with a molten center. An impressive dessert that's easier than you think.",
    ingredients: [
      "6 oz dark chocolate (70%)",
      "1/2 cup unsalted butter",
      "2 large eggs",
      "2 egg yolks",
      "1/4 cup sugar",
      "2 tbsp all-purpose flour",
      "Pinch of salt",
      "Butter and cocoa for ramekins",
      "Vanilla ice cream for serving",
    ],
    steps: [
      "Preheat oven to 425°F. Butter and dust 4 ramekins with cocoa powder.",
      "Melt chocolate and butter together in a double boiler or microwave.",
      "Whisk eggs, egg yolks, and sugar until thick and pale.",
      "Fold melted chocolate into egg mixture.",
      "Sift in flour and salt, fold gently until just combined.",
      "Divide batter among ramekins. Can refrigerate for up to 8 hours at this point.",
      "Bake for 12-14 minutes until edges are set but center jiggles.",
      "Let cool 1 minute, run a knife around edges, invert onto plates.",
      "Serve immediately with vanilla ice cream.",
    ],
    tags: ["Dessert", "Chocolate", "French"],
    prepTime: 15,
    cookTime: 14,
    servings: 4,
    isFavorite: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "5",
    slug: "spicy-black-bean-tacos",
    title: "Spicy Black Bean Tacos",
    description:
      "Quick and flavorful vegetarian tacos with seasoned black beans, fresh pico de gallo, and creamy avocado.",
    ingredients: [
      "2 cans black beans, drained",
      "1 tsp cumin",
      "1 tsp smoked paprika",
      "1/2 tsp cayenne pepper",
      "8 corn tortillas",
      "2 avocados",
      "1 cup pico de gallo",
      "1/2 cup crumbled cotija cheese",
      "Fresh cilantro",
      "Lime wedges",
    ],
    steps: [
      "Heat black beans in a pan with cumin, paprika, cayenne, and a splash of water.",
      "Mash half the beans roughly, leaving the rest whole for texture.",
      "Warm tortillas on a dry skillet until lightly charred.",
      "Slice avocados and prepare pico de gallo if not store-bought.",
      "Assemble tacos: beans, avocado, pico, cotija, and cilantro.",
      "Squeeze lime over the top and serve immediately.",
    ],
    tags: ["Mexican", "Vegetarian", "Quick"],
    prepTime: 10,
    cookTime: 10,
    servings: 4,
    isFavorite: false,
    createdAt: new Date().toISOString(),
  },
];
